### ISSUE TITLE
mouse pointer not focused or lost cursor sprite on window border

### ISSUE THREAD

**Issue by olevole** [FreeBSDDesktop/freebsd-base-graphics#102]
drm-next-4.7 f16dfbd, Iris Graphics 540, xorg-server-1.18.4,1 from https://github.com/freebsd/freebsd-ports-graphics.

when you try in any WM to move set  the cursor to the edge of the window (for example, to resize it), pointer slips/jump from focus, or cursor not switch to another sprite. However, the window can be resized  if the mouse is on a few pixels from border.

A similar problem with the select text in (xterm, konsole ...) - the string was selected which is much lower than the pointer. 

Also, this is only visual effect. I've record X session via recordmydesktop and if you watch it on

https://www.olevole.ru/beautifullife.ogv - all looks fine.

But what i see in real, recorded on phone ;):

https://www.olevole.ru/reallife.mp4

**Comment by nomadlogic** [comment]
+1 I have been having this issue for quite a while on Skylake and drm-next codebranch.  I am open to ideas as to how we can debug this, as I've not been able to make much progress over the past couple months.  It is good to hear its happening to someone else actually - as I was affraid it was just a misconfig on my end.

FWIW if using modesetting driver this option should fix 'er up:

Option      "SWcursor"    "on"

**Comment by olevole** [comment]
No, i used "intel" driver and this options not affected for me.

**Comment by TheDharc** [comment]
I don't know why they are not fixing bugs =/

**Comment by mattmacy** [comment]
Can you confirm that this issue isn't present on linux 4.7?

**Comment by TheDharc** [comment]
Ok, fixed in last trueos update.

**Comment by olevole** [comment]
@TheDharc Hi. Can you share link to patch/commit that fix this problem? I've use FreeBSD, not TrueOS.

**Comment by mattmacy** [comment]
Fixed in drm-next
