### ISSUE TITLE
amdgpu option to support SI cards

### ISSUE THREAD

**Issue by girivs** [FreeBSDDesktop/freebsd-base-graphics#106]
CONFIG_DRM_AMDGPU_CIK=Y
CONFIG_DRM_AMDGPU_SI=Y (linux 4.9)

Can an option be provided to compile with these defined in order to take advantage of this?

**Comment by mattmacy** [comment]
I'm happy to do this, but I think the amdgpu driver is less stable than radeon at the moment.

**Comment by mattmacy** [comment]
(On FreeBSD)

**Comment by girivs** [comment]
Understood. Having the option is good though, when it does get more stable. I confirmed this works with Linux, just to make sure upstream is stable.

**Comment by mattmacy** [comment]
It's now enabled by default- not sure about cik.
