### ISSUE TITLE
Intel P4600/P4700: Crash in vt_kms_postswich() under heavy system load

### ISSUE THREAD

**Issue by baitisj** [FreeBSDDesktop/freebsd-base-graphics#107]
- VirtualBox / Windows 10 guest OS
- SNA acceleration
- Maximum system load

Just using the VM. Nothing special, really.

Result:
> vt_kms_postswitch() at vt_kms_postswitch+0x48/frame 0xfffffe005c3ee4b0
> vt_window_switch() at vt_window_switch+0x145/frame 0xfffffe085c3ee50
> vtterm_cngrab() at vtterm_cngrab+0x20/frame 0xffffffe085c3ee520
> cngrab() at cngrab+0x32/frame 0xfffffe085c3ee540
> vpanic()...
> panic()...
> vm_radix_insert()...
> vm_page_alloc()
> vm_fault_hold()
> vm_fault()

![20161209_114234](https://cloud.githubusercontent.com/assets/12502877/21064577/5552d62a-be10-11e6-8e65-a8dfe0e3149e.jpg)

Xorg.0.log:

> [   278.803] 
> X.Org X Server 1.18.4
> Release Date: 2016-07-19
> [   278.803] X Protocol Version 11, Revision 0
> [   278.803] Build Operating System: FreeBSD 12.0-CURRENT amd64 
> [   278.804] Current Operating System: FreeBSD raid.baitis.home 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC amd64
> [   278.804] Build Date: 27 October 2016  03:26:29PM
> [   278.804]  
> [   278.804] Current version of pixman: 0.34.0
> [   278.804] 	Before reporting problems, check http://wiki.x.org
> 	to make sure that you have the latest version.
> [   278.804] Markers: (--) probed, (**) from config file, (==) default setting,
> 	(++) from command line, (!!) notice, (II) informational,
> 	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> [   278.804] (==) Log file: "/var/log/Xorg.0.log", Time: Fri Dec  9 11:17:59 2016
> [   278.804] (==) Using system config directory "/usr/local/share/X11/xorg.conf.d"
> [   278.804] (==) No Layout section.  Using the first Screen section.
> [   278.804] (==) No screen section available. Using defaults.
> [   278.804] (**) |-->Screen "Default Screen Section" (0)
> [   278.804] (**) |   |-->Monitor "<default monitor>"
> [   278.804] (==) No monitor specified for screen "Default Screen Section".
> 	Using a default monitor configuration.
> [   278.804] (==) Automatically adding devices
> [   278.804] (==) Automatically enabling devices
> [   278.804] (==) Not automatically adding GPU devices
> [   278.804] (==) Max clients allowed: 256, resource mask: 0x1fffff
> [   278.804] (==) FontPath set to:
> 	/usr/local/share/fonts/misc/,
> 	/usr/local/share/fonts/TTF/,
> 	/usr/local/share/fonts/OTF/,
> 	/usr/local/share/fonts/Type1/,
> 	/usr/local/share/fonts/100dpi/,
> 	/usr/local/share/fonts/75dpi/
> [   278.804] (==) ModulePath set to "/usr/local/lib/xorg/modules"
> [   278.804] (II) The server relies on devd to provide the list of input devices.
> 	If no devices become available, reconfigure devd or disable AutoAddDevices.
> [   278.805] (II) Loader magic: 0x811b10
> [   278.805] (II) Module ABI versions:
> [   278.805] 	X.Org ANSI C Emulation: 0.4
> [   278.805] 	X.Org Video Driver: 20.0
> [   278.805] 	X.Org XInput driver : 22.1
> [   278.805] 	X.Org Server Extension : 9.0
> [   278.805] (--) PCI:*(0:0:2:0) 8086:041a:1028:0620 rev 6, Mem @ 0xf7800000/4194304, 0xe0000000/268435456, I/O @ 0x0000f000/64, BIOS @ 0x????????/65536
> [   278.805] (II) LoadModule: "glx"
> [   278.805] (II) Loading /usr/local/lib/xorg/modules/extensions/libglx.so
> [   278.808] (II) Module glx: vendor="NVIDIA Corporation"
> [   278.808] 	compiled for 4.0.2, module version = 1.0.0
> [   278.808] 	Module class: X.Org Server Extension
> [   278.808] (II) NVIDIA GLX Module  367.44  Wed Aug 17 22:01:17 PDT 2016
> [   278.808] (==) Matched intel as autoconfigured driver 0
> [   278.808] (==) Matched fbdev as autoconfigured driver 1
> [   278.808] (==) Matched vesa as autoconfigured driver 2
> [   278.808] (==) Assigned the driver to the xf86ConfigLayout
> [   278.808] (II) LoadModule: "intel"
> [   278.808] (II) Loading /usr/local/lib/xorg/modules/drivers/intel_drv.so
> [   278.808] (II) Module intel: vendor="X.Org Foundation"
> [   278.808] 	compiled for 1.18.4, module version = 2.99.917
> [   278.808] 	Module class: X.Org Video Driver
> [   278.808] 	ABI class: X.Org Video Driver, version 20.0
> [   278.808] (II) LoadModule: "fbdev"
> [   278.809] (WW) Warning, couldn't open module fbdev
> [   278.809] (II) UnloadModule: "fbdev"
> [   278.809] (II) Unloading fbdev
> [   278.809] (EE) Failed to load module "fbdev" (module does not exist, 0)
> [   278.809] (II) LoadModule: "vesa"
> [   278.809] (II) Loading /usr/local/lib/xorg/modules/drivers/vesa_drv.so
> [   278.809] (II) Module vesa: vendor="X.Org Foundation"
> [   278.809] 	compiled for 1.18.4, module version = 2.3.4
> [   278.809] 	Module class: X.Org Video Driver
> [   278.809] 	ABI class: X.Org Video Driver, version 20.0
> [   278.809] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
> 	i810, i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G,
> 	915G, E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM,
> 	Pineview G, 965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33,
> 	GM45, 4 Series, G45/G43, Q45/Q43, G41, B43
> [   278.809] (II) intel: Driver for Intel(R) HD Graphics: 2000-6000
> [   278.809] (II) intel: Driver for Intel(R) Iris(TM) Graphics: 5100, 6100
> [   278.809] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics: 5200, 6200, P6300
> [   278.809] (II) VESA: driver for VESA chipsets: vesa
> [   278.809] (--) Using syscons driver with X support (version 16777218.0)
> [   278.809] (--) using VT number 9
> 
> [   278.810] (II) intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20160425
> [   278.810] (WW) Falling back to old probe method for vesa
> [   278.810] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
> [   278.811] (--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics P4600/P4700
> [   278.811] (--) intel(0): CPU: x86-64, sse2, sse3, ssse3, sse4.1, sse4.2, avx, avx2; using a maximum of 2 threads
> [   278.811] (II) intel(0): Creating default Display subsection in Screen section
> 	"Default Screen Section" for depth/fbbpp 24/32
> [   278.811] (==) intel(0): Depth 24, (--) framebuffer bpp 32
> [   278.811] (==) intel(0): RGB weight 888
> [   278.811] (==) intel(0): Default visual is TrueColor
> [   278.811] (II) intel(0): Output VGA1 has no monitor section
> [   278.811] (II) intel(0): Enabled output VGA1
> [   278.811] (II) intel(0): Output DP1 has no monitor section
> [   278.811] (II) intel(0): Enabled output DP1
> [   278.811] (II) intel(0): Output HDMI1 has no monitor section
> [   278.811] (II) intel(0): Enabled output HDMI1
> [   278.811] (II) intel(0): Output DP2 has no monitor section
> [   278.811] (II) intel(0): Enabled output DP2
> [   278.811] (II) intel(0): Output HDMI2 has no monitor section
> [   278.811] (II) intel(0): Enabled output HDMI2
> [   278.811] (--) intel(0): Using a maximum size of 256x256 for hardware cursors
> [   278.811] (II) intel(0): Output VIRTUAL1 has no monitor section
> [   278.811] (II) intel(0): Enabled output VIRTUAL1
> [   278.811] (--) intel(0): Output DP1 using initial mode 2560x1080 on pipe 0
> [   278.811] (==) intel(0): TearFree disabled
> [   278.811] (==) intel(0): DPI set to (96, 96)
> [   278.811] (II) Loading sub module "dri2"
> [   278.811] (II) LoadModule: "dri2"
> [   278.811] (II) Module "dri2" already built-in
> [   278.811] (II) Loading sub module "present"
> [   278.811] (II) LoadModule: "present"
> [   278.811] (II) Module "present" already built-in
> [   278.811] (II) UnloadModule: "vesa"
> [   278.811] (II) Unloading vesa
> [   278.811] (==) Depth 24 pixmap format is 32 bpp
> [   278.812] (II) intel(0): SNA initialized with Haswell (gen7.5, gt2) backend
> [   278.812] (==) intel(0): Backing store enabled
> [   278.812] (==) intel(0): Silken mouse enabled
> [   278.812] (II) intel(0): HW Cursor enabled
> [   278.812] (II) intel(0): RandR 1.2 enabled, ignore the following RandR disabled message.
> [   278.812] (==) intel(0): DPMS enabled
> [   278.812] (II) intel(0): [DRI2] Setup complete
> [   278.812] (II) intel(0): [DRI2]   DRI driver: i965
> [   278.812] (II) intel(0): [DRI2]   VDPAU driver: va_gl
> [   278.812] (II) intel(0): direct rendering: DRI2 enabled
> [   278.812] (II) intel(0): hardware support for Present enabled
> [   278.812] (--) RandR disabled
> [   278.812] (EE) Failed to initialize GLX extension (Compatible NVIDIA X driver not found)
> [   278.814] (II) intel(0): switch to mode 2560x1080@60.0 on DP1 using pipe 0, position (0, 0), rotation normal, reflection none
> [   278.814] (II) intel(0): Setting screen physical size to 677 x 285
> [   278.876] (II) config/devd: probing input devices...
> [   278.876] (II) config/devd: adding input device (null) (/dev/kbdmux)
> [   278.876] (II) LoadModule: "kbd"
> [   278.876] (II) Loading /usr/local/lib/xorg/modules/input/kbd_drv.so
> [   278.876] (II) Module kbd: vendor="X.Org Foundation"
> [   278.876] 	compiled for 1.18.4, module version = 1.8.1
> [   278.876] 	Module class: X.Org XInput Driver
> [   278.876] 	ABI class: X.Org XInput driver, version 22.1
> [   278.876] (II) Using input driver 'kbd' for 'kbdmux'
> [   278.876] (**) kbdmux: always reports core events
> [   278.876] (**) kbdmux: always reports core events
> [   278.876] (**) Option "Protocol" "standard"
> [   278.876] (**) Option "XkbRules" "base"
> [   278.877] (**) Option "XkbModel" "pc105"
> [   278.877] (**) Option "XkbLayout" "us"
> [   278.877] (**) Option "config_info" "devd:kbdmux"
> [   278.877] (II) XINPUT: Adding extended input device "kbdmux" (type: KEYBOARD, id 6)
> [   278.877] (II) config/devd: kbdmux is enabled, ignoring device ukbd0
> [   278.877] (II) config/devd: kbdmux is enabled, ignoring device atkbd0
> [   278.877] (II) config/devd: adding input device (null) (/dev/sysmouse)
> [   278.877] (II) LoadModule: "mouse"
> [   278.877] (II) Loading /usr/local/lib/xorg/modules/input/mouse_drv.so
> [   278.877] (II) Module mouse: vendor="X.Org Foundation"
> [   278.877] 	compiled for 1.18.4, module version = 1.9.1
> [   278.877] 	Module class: X.Org XInput Driver
> [   278.877] 	ABI class: X.Org XInput driver, version 22.1
> [   278.877] (II) Using input driver 'mouse' for 'sysmouse'
> [   278.877] (**) sysmouse: always reports core events
> [   278.877] (**) Option "Device" "/dev/sysmouse"
> [   278.877] (==) sysmouse: Protocol: "Auto"
> [   278.877] (**) sysmouse: always reports core events
> [   278.877] (==) sysmouse: Emulate3Buttons, Emulate3Timeout: 50
> [   278.877] (**) sysmouse: ZAxisMapping: buttons 4 and 5
> [   278.877] (**) sysmouse: Buttons: 5
> [   278.877] (**) Option "config_info" "devd:sysmouse"
> [   278.877] (II) XINPUT: Adding extended input device "sysmouse" (type: MOUSE, id 7)
> [   278.877] (**) sysmouse: (accel) keeping acceleration scheme 1
> [   278.877] (**) sysmouse: (accel) acceleration profile 0
> [   278.877] (**) sysmouse: (accel) acceleration factor: 2.000
> [   278.877] (**) sysmouse: (accel) acceleration threshold: 4
> [   278.877] (II) sysmouse: SetupAuto: hw.iftype is 4, hw.model is 0
> [   278.877] (II) sysmouse: SetupAuto: protocol is SysMouse
> [   278.877] (II) config/devd: device /dev/ums0 already opened
> [   278.903] (II) intel(0): EDID vendor "GSM", prod id 23026
> [   278.903] (II) intel(0): Using EDID range info for horizontal sync
> [   278.903] (II) intel(0): Using EDID range info for vertical refresh
> [   278.903] (II) intel(0): Printing DDC gathered Modelines:
> [   278.903] (II) intel(0): Modeline "2560x1080"x0.0  185.58  2560 2624 2688 2784  1080 1083 1093 1111 -hsync -vsync (66.7 kHz eP)
> [   278.903] (II) intel(0): Modeline "1920x1080"x0.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 +hsync -vsync (67.5 kHz e)
> [   278.903] (II) intel(0): Modeline "1920x1080"x0.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 +hsync +vsync (67.5 kHz e)
> [   278.903] (II) intel(0): Modeline "1920x1080i"x0.0   74.25  1920 2008 2052 2200  1080 1084 1094 1125 interlace +hsync +vsync (33.8 kHz e)
> [   278.903] (II) intel(0): Modeline "1280x720"x0.0   74.25  1280 1390 1430 1650  720 725 730 750 +hsync +vsync (45.0 kHz e)
> [   278.903] (II) intel(0): Modeline "720x480"x0.0   27.00  720 736 798 858  480 489 495 525 -hsync -vsync (31.5 kHz e)
> [   278.903] (II) intel(0): Modeline "800x600"x0.0   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz e)
> [   278.903] (II) intel(0): Modeline "640x480"x0.0   31.50  640 656 720 840  480 481 484 500 -hsync -vsync (37.5 kHz e)
> [   278.903] (II) intel(0): Modeline "640x480"x0.0   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
> [   278.903] (II) intel(0): Modeline "720x400"x0.0   28.32  720 738 846 900  400 412 414 449 -hsync +vsync (31.5 kHz e)
> [   278.903] (II) intel(0): Modeline "1280x1024"x0.0  135.00  1280 1296 1440 1688  1024 1025 1028 1066 +hsync +vsync (80.0 kHz e)
> [   278.903] (II) intel(0): Modeline "1024x768"x0.0   78.75  1024 1040 1136 1312  768 769 772 800 +hsync +vsync (60.0 kHz e)
> [   278.903] (II) intel(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
> [   278.903] (II) intel(0): Modeline "800x600"x0.0   49.50  800 816 896 1056  600 601 604 625 +hsync +vsync (46.9 kHz e)
> [   278.903] (II) intel(0): Modeline "1152x864"x0.0  108.00  1152 1216 1344 1600  864 865 868 900 +hsync +vsync (67.5 kHz e)
> [   278.903] (II) intel(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
> [   278.903] (II) intel(0): Modeline "1280x720"x60.0   74.48  1280 1336 1472 1664  720 721 724 746 -hsync +vsync (44.8 kHz e)
> [   278.903] (II) intel(0): Modeline "1600x900"x60.0  119.00  1600 1696 1864 2128  900 901 904 932 -hsync +vsync (55.9 kHz e)
> [   278.903] (II) intel(0): Modeline "1680x1050"x0.0  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync (65.3 kHz e)
> [   278.903] (II) intel(0): Modeline "720x576"x0.0   27.00  720 732 796 864  576 581 586 625 -hsync -vsync (31.2 kHz e)
> [   278.903] (II) intel(0): Modeline "1440x576i"x0.0   27.00  1440 1464 1590 1728  576 580 586 625 interlace -hsync -vsync (15.6 kHz e)
> [   278.903] (II) intel(0): Modeline "1280x720"x0.0   74.25  1280 1720 1760 1980  720 725 730 750 +hsync +vsync (37.5 kHz e)
> [   278.903] (II) intel(0): Modeline "1440x480i"x0.0   27.00  1440 1478 1602 1716  480 488 494 525 interlace -hsync -vsync (15.7 kHz e)
> [   278.903] (II) intel(0): Modeline "1920x1080"x0.0   74.25  1920 2558 2602 2750  1080 1084 1089 1125 +hsync +vsync (27.0 kHz e)
> [   278.903] (II) intel(0): Modeline "1920x1080i"x0.0   74.25  1920 2448 2492 2640  1080 1084 1094 1125 interlace +hsync +vsync (28.1 kHz e)
>

**Comment by valpackett** [comment]
> Software graphics rendering

Your log actually mentions running SNA on Haswell.

> [ 278.812] (II) intel(0): SNA initialized with Haswell (gen7.5, gt2) backend

I'm running SNA on Haswell too, and I got this crash a few times. I don't think it's related to load??

- got it some time (a significant amount of time!) *after* the `sway` Wayland compositor unkillably froze into a `kqflx` state
- got it when making a screenshot with [maim](https://github.com/naelstrof/maim)
- got it when i was experimenting with starting compiz/emerald

**Comment by valpackett** [comment]
Here's a couple screens. Interestingly, on one of them the `postswitch` error is combined with a page fault (#96??). The other one involves `assfail3` which uh… looks like the linux graphics stack is a total ass fail :D
![img_20161211_203247](https://cloud.githubusercontent.com/assets/208340/21083188/0ae9515c-bffc-11e6-83f7-9575ced5d622.jpg)
![img_20161211_223528](https://cloud.githubusercontent.com/assets/208340/21083187/0ae8b62a-bffc-11e6-9481-d10361d26467.jpg)

**Comment by mattmacy** [comment]
FYI, postswitch means nothing by itself - it's what the driver calls to switch to console on panic. Blaming it is like blaming panic.

**Comment by mattmacy** [comment]
Assfail3 is in the Solaris layer. It's either a bug in ZFS or a memory corruption.

**Comment by valpackett** [comment]
Yeah it might be that the graphics driver is corrupting memory…

**Comment by mattmacy** [comment]
Precisely. Not fun to track down.

**Comment by baitisj** [comment]
Thanks for clarifying wrt SNA; fixing original report

**Comment by valpackett** [comment]
woah this was a commit that refers to the same issue number in a different repo probably (the openzfs repo?)

**Comment by markjdb** [comment]
Heh. :)

Is this still an issue? There have been many fixes for various memory management issues since the last comment here.

**Comment by valpackett** [comment]
yeah I haven't seen these crashes recently. though I wasn't using my laptop as often…

**Comment by baitisj** [comment]
No issues for quite some time. Closing.
