### ISSUE TITLE
Panic on i915kms load with AGP cards

### ISSUE THREAD

**Issue by Juanitou** [FreeBSDDesktop/freebsd-base-graphics#11]
(Opening this issue to track AGP support, which has not been upgraded yet. Reference: [freebsd-X11 mailing list](https://lists.freebsd.org/pipermail/freebsd-x11/2016-May/017605.html).)

There is a regression in AGP with the DRM 4.6 kernel. `kldoad i915kms` crashes the system with at least two Intel GMA processors:
- G41 Express (desktop, EagleLake).
- GM45 (mobile, Cantiga).

Those chips work very well with the 3.9 version of DRM.

**Comment by mattmacy** [comment]
I've ordered a T410 which is Arrandale based and thus relies on AGP support as well. It will get here next week. I fill in the missing bits as soon as I can test.

**Comment by mattmacy** [comment]
The Thinkpad T410 has a processor with integrated graphics but only exposes the discrete nvidia chipset:
 https://gist.github.com/mattmacy/2c2ea2783b9fc28363450735a0cc326d

http://www.thinkwiki.org/wiki/Intel_HD_Graphics

Evidently those with discrete nvidia chips don't allow the integrated graphics to be enabled.

It's hard finding anything that old that works. Can you recommend something?

Thanks.

**Comment by Juanitou** [comment]
> It's hard finding anything that old that works. Can you recommend something?

Sorry, no.

**Comment by Juanitou** [comment]
As of cd1bbc304e6897eec1c422f9abcb4325e1ada2d0, this issue is solved for the chips I can have access to: G41 Express (desktop, EagleLake).and GM45 (mobile, Cantiga). Thanks!

**Comment by mattmacy** [comment]
There are still issues, but it no longer panics on load. Let me know if you think it should be reopened.
