### ISSUE TITLE
Clang fails to build after repo merge

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [FreeBSDDesktop/freebsd-base-graphics#113]
Hello
I cloned a fresh shallow repo of merged tree (drm-next) with flag "--depth 1".
Clang fails to build, as confirmed by,
* No /usr/bin/cc in fresh DESTDIR target
* cc on host has date of last build (pre-merge)
* work directory has empty tmp/usr/lib/clang/3.9.1 (sub folders are empty), same with tmp/legacy/usr/lib/Clang./3.9.1
* Explicitly setting CLANG knobs in /etc/src.conf has no effect, neither does disabling ccache. 

I ran in to this problem while trying to debug build problems in the poudrière jail.
Currently have no Xorg, was trying to re-build all relevant ports before proceeding with debug.
Regards.

**Comment by Beeblebrox-BSD** [comment]
* Clarification:
The problem is not with a shallow git repo, as I ran "git --unshallow" and got same resuılt. Also, "make toolchain" does nothing to resolve the issue.

* Update:
With latest kernel, if I kldload drm, then radeonkms vt works fine as expected, however dmesg does repeatedly show:
[drm:radeon_vga_detect] VGA-1: probed a monitor but no|invalid EDID

When I start xorg, kernel panics and crashes (using vesa for xorg atm)
I am emailing Matt separately for the kernel dumps, should he want them.

**Comment by hselasky** [comment]
Hi,

Can you re-test using the latest drm-next branch?

--HPS

**Comment by Beeblebrox-BSD** [comment]
Hello Peter,
I tried the following two alternatives but clang still does not build
* Renamed /etc/src.conf to buildworld with defaults
* Explicitly set all clang flags in src.conf
I only see usr/bin/c++filt and folders
usr/lib/debug/usr/lib/clang,  usr/lib/clang
have sub-folders which are just empty.

I tried several independent make calls, idk whether this helps:
* make -C usr.bin/clang =>
In file included from /asp/git/src/contrib/llvm/tools/clang/tools/driver/cc1_main.cpp:18:
In file included from /asp/git/src/contrib/llvm/tools/clang/include/clang/Driver/DriverDiagnostic.h:13:
In file included from /asp/git/src/contrib/llvm/tools/clang/include/clang/Basic/Diagnostic.h:18:
/asp/git/src/contrib/llvm/tools/clang/include/clang/Basic/DiagnosticIDs.h:53:10: fatal error: 
      'clang/Basic/DiagnosticCommonKinds.inc' file not found
#include "clang/Basic/DiagnosticCommonKinds.inc"

* make -C lib/clang =>
===> libllvm (all)
llvm-tblgen -gen-attrs  -I /asp/git/src/contrib/llvm/include -d llvm/IR/Attributes.inc.d -o llvm/IR/Attributes.inc  /asp/git/src/contrib/llvm/include/llvm/IR/Attributes.td
llvm-tblgen: error opening llvm/IR/Attributes.inc:No such file or directory
*** Error code 1

Regards.
-- 
FreeBSD_amd64_12
Please CC my email when responding, mail from list is not delivered.

**Comment by hselasky** [comment]
Hi,
I'm just using world from 12-current and only the kernel from DRM next.
--HPS

**Comment by PhilPotter** [comment]
Clang build is disabled in this repo by various tweaks, I have a patch if you want to build it but I'm leaning towards just grabbing the kernel as I still get the same DiagnosticCommonKinds.inc error with it.

**Comment by Beeblebrox-BSD** [comment]
Thanks for the info.
I'll go with kernel-only on the repo as HPS had also advised.

You can close the PR if you wish.

PS advise if anyone wants the kernel dumps as noted previously; I don't
want to paste the link publicly.

Regards.

Clang build is disabled in this repo by various tweaks, I have a patch if
you want to build it but I'm leaning towards just grabbing the kernel as I
still get the same DiagnosticCommonKinds.inc error with it.
