### ISSUE TITLE
http://www.bsddesktop.com down

### ISSUE THREAD

**Issue by MissingNoIOI** [FreeBSDDesktop/freebsd-base-graphics#116]
I'm not quite sure if this is the right place to report this, but http://www.bsddesktop.com seems to be down, which makes installing the new Xorg kinda hard

**Comment by grahamperrin** [comment]
http://www.google.co.uk/search?q=bsddesktop.com+site:github.com/FreeBSDDesktop

> …  did not match any documents.

http://web.archive.org/web/20160610230643/http://www.bsddesktop.com:80/ just one capture, 

> Welcome to nginx! … 

http://isup.me/http://www.bsddesktop.com

http://whois.domaintools.com/bsddesktop.com

**Comment by MissingNoIOI** [comment]
The domain gets mentioned here in the [Wiki](https://github.com/FreeBSDDesktop/freebsd-base-graphics/wiki), maybe it has to be updated then?:

#### Using Binary Packages

There is a pkg repository available at the following co-ordinates which has prebuilt binaries of the Xorg code that is suitable for the drm-next-4.7 branch:
```
FreeBSD-ports: {
  url: "http://www.bsddesktop.com/images/120amd64-ports-graphics-xserver-mesa-next/"
  enabled: yes
}
```

**Comment by mattmacy** [comment]
I'm not using that any more. Sorry.
