### ISSUE TITLE
drm 4.6 - GNOME: artifacts

### ISSUE THREAD

**Issue by kwm81** [FreeBSDDesktop/freebsd-base-graphics#12]
Really noticeable in text, but the "animated" gnome menus glitch out also.

**Comment by kwm81** [comment]
A quick check doesn't show any difference when using AccelMethod uxa or sna.

**Comment by kwm81** [comment]
Example of how the problem with GNOME looks:
![i915-drm4 6-2016-05-31](https://cloud.githubusercontent.com/assets/1414015/15726103/5ba428aa-284f-11e6-93d6-23cd9a674c9a.png)

**Comment by mishurov** [comment]
I have the same issue with fonts in Openbox.

**Comment by mishurov** [comment]
A similar problem existed in Linux too. There're the links:
https://bugs.freedesktop.org/show_bug.cgi?id=88584
http://askubuntu.com/questions/584922/how-do-i-fix-fonts-not-rendering-and-missing-letters

**Comment by kwm81** [comment]
Status update:
branch drm-next-4.6 3c0e357 on my Sandybridge running with Xorg with the modesetting driver.

Missing letters in the menus, totaly messed up mate-terminal window and mate-terminal about window.

![drm-4 6-mate-1-aug-2016](https://cloud.githubusercontent.com/assets/1414015/17287097/eacee260-57cd-11e6-8964-c352b6267774.jpg)

**Comment by kwm81** [comment]
Really really quick test, no long term testing done.

So SNA looks to work fine. The menus, icons on the desktop and mate-terminal are fine.
UXA is a differnt story. Menu looks fine, same for mate-terminal (even if the command line is hidden behind the menu in the screenshot). But the icons on the desktop are screwed up :)

![drm-4 6-mate-uxa](https://cloud.githubusercontent.com/assets/1414015/17308091/7176c2d2-5838-11e6-8d2b-7c2ed705de29.jpg)

**Comment by kwm81** [comment]
Ok so after testing SNA a bit the garbled text problem is still there, even if it not so worse as it has been.

**Comment by martincahil** [comment]
I have a exactly same problem. In my case, Icon is fine but text is corrupted. I really want to know how to fix it. If anyone know where the problem is occurred, tell me please. Thank you for your answer.
