### ISSUE TITLE
single user mode illegible (torn), Intel HD Graphics 5500, UEFI

### ISSUE THREAD

**Issue by grahamperrin** [FreeBSDDesktop/freebsd-base-graphics#130]
HP EliteBook 850 G2. When booted with UEFI without CSM in single user mode, the screen is illegible: 

![photostudio_1489389629084](https://cloud.githubusercontent.com/assets/192271/24027210/ac0ab646-0abd-11e7-8321-9ded3330427d.jpg)

TrueOS Desktop, recent but (sorry) version unknown. Mentioned 2017-03-13 20:17 in irc://irc.efnet.org/#freebsd-xorg

(This is an old issue that I treated as negligible when CSM was a workaround, but CSM no longer works around.)

**Comment by hselasky** [comment]
Hi, There has been some patches after the 13th of March, to update the firmware files used. It might affect your device. --HPS
