### ISSUE TITLE
panic on resume using XFCE4

### ISSUE THREAD

**Issue by nomadlogic** [FreeBSDDesktop/freebsd-base-graphics#138]
I can reproduce a panic under the following conditions:

- use XFCE4 window manager
- start XFCE4 with external HDMI monitor connected
- remove HDMI display
- put laptop to sleep (enter S3 state via closing laptop)
- open lid after system had entered S3
- panic

`panic: mutex Gian owned at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_synch.c:394
`

Interestingly enough I can not reproduce this panic with Mate.  Here is a screenshot of the panic:
https://goo.gl/photos/ASKBvJi3erBrWCvVA

**Comment by markjdb** [comment]
Could you please give this patch a try? https://people.freebsd.org/~markj/patches/linuxkpi_drop_giant.diff

**Comment by nomadlogic** [comment]
Rad, this seems to fix it up.  I'll dog-food XFCE4 for a couple days to be sure, but I am unable to reproduce this after applying your patch.

Thanks!

**Comment by markjdb** [comment]
Excellent, thanks for testing.

**Comment by markjdb** [comment]
The change was committed to FreeBSD as r317148. It'll get picked up in the next merge.
