### ISSUE TITLE
Remove clang detection for version "4.0"

### ISSUE THREAD

**Issue by seanbruno** [FreeBSDDesktop/freebsd-base-graphics#139]
Since FreeBSD now has clang version 4 in base, there's no need to restrict to version 4, nor is there a reason to *not* build CC

https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/877da00c1b4e843c90ac44405b9d2f159bca3ef7

https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/d0f0a3dbadfa1fb6bfbaa22eedde8b4fc3522182
https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/7e02ee4a000a704b95b09f768c11f08fb5a72dab

**Comment by seanbruno** [comment]
https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/2372fe603e3042bda300a7148960f4706bd8e2fe#diff-82b699c9fe215be7faeab9e345f73f3b

Oh, and enable clang builds and SVN by default.

**Comment by nomadlogic** [comment]
IIRC one of the original reasons for not building clang during buildworld was to help us get quicker builds so allowing for more iterations while testing.  I've actually been pretty happy with this on my end so I'm not sure what we are missing by not building this.

**Comment by seanbruno** [comment]
I too enjoy the faster build times.  However, this is required to use base as a jail for poudriere.  :-(

**Comment by nomadlogic** [comment]
Ah understood - thanks for the clarification @seanbruno!  I'll step aside and allow the maintainers to do their job now :)

**Comment by hselasky** [comment]
I have some local patches too to remove the clang detection and can confirm this works as expected.

**Comment by seanbruno** [comment]
It looks like we can just "restore" the files that were changed, do you want a pull req to do this or do you want to just "cp" the files from FreeBSD?

/usr/src % git status
On branch drm-next
Your branch is up-to-date with 'origin/drm-next'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Makefile.inc1
	modified:   lib/Makefile
	modified:   usr.bin/Makefile

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by hselasky** [comment]
Hi,

The files should be cp'ed from the master branch of drm-next. It contains the last copy of the FreeBSD -current sources which were integrated. @markjdb Any objections?

--HPS

**Comment by markjdb** [comment]
No, fine with me.

I hadn't updated drm-next/master after the most recent merge. I updated it a couple of minutes ago, so be sure to re-pull.

**Comment by hselasky** [comment]
This issue should be fixed as of my latest drm-next commit.
