### ISSUE TITLE
Skylake no longer resumes

### ISSUE THREAD

**Issue by trombonehero** [FreeBSDDesktop/freebsd-base-graphics#142]
It's been awhile since I've been able to test `drm-next`, but after updating to f7745ad (from, er, something at least a month old), my Skylake system no longer resumes. Pressing the power button doesn't cause an ACPI shutdown, so something seems to be firmly wedged.

**Comment by trombonehero** [comment]
I attempted to do a `git bisect` with just `buildkernel`/`installkernel`, but that doesn't seem to cause the i915 drm bits to initialize properly: there is no `/dev/drm` directory. Do I need a full `buildworld buildkernel installkernel installworld` on every iteration of the bisection?

**Comment by hselasky** [comment]
drm-next only patch the kernel

**Comment by trombonehero** [comment]
Whenever I build and install an older kernel (even one as recent as dfcc5fbd), I get the following output from `kldload i915kms`:

```
info: [drm] Initialized drm 1.1.0 20060810
```

Also, the mode doesn't actually switch and no `/dev/dri` appears. Running `kldload i915kms` on a recent (world-matching?) kernel gives me 688 lines of output together with a mode switch and all of the expected-normal behaviour (except for a lack of suspend/resume). Is there something on the filesystem that `i915kms.ko` needs? Could it have something to do with the version of LLVM that's used to build the module?

**Comment by trombonehero** [comment]
The patch at https://lists.freebsd.org/pipermail/freebsd-current/2017-May/065917.html causes my machine to resume again. There are visual artifacts that make the display unusable, but that seems like a separate bug, as those were around in 390597e too (whereas others in Issue #145 report that commit as a "last known good" version).
