### ISSUE TITLE
ValleyView: screen corruption after starting "chrome"

### ISSUE THREAD

**Issue by freebsd-nils-level1** [FreeBSDDesktop/freebsd-base-graphics#15]
Xorg and KDE4 run well; but after running "chrome" screen corruption occurs. Afterwards, text of the KDE menus seems to be okay.

Here's my "/var/log/messages":

[valleyview.drm.log.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/297994/valleyview.drm.log.txt)

Tried using "xf86-intel-video" in versions 2.21.15_9 and the manually built 2.99.917. No difference. AccelMethod "SNA" is unusable in 2.99.917

Switching between Xorg and console works well - even after corruption has started. My laptop: "Lenovo G50-30" with
`
vgapci0@pci0:0:2:0:     class=0x030000 card=0x381817aa chip=0x0f318086 rev=0x0e hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Atom Processor Z36xxx/Z37xxx Series Graphics & Display'
    class      = display
    subclass   = VGA
`
and
`
vgapci1@pci0:1:0:0:     class=0x030200 card=0x381817aa chip=0x114010de rev=0xa1 hdr=0x00
    vendor     = 'NVIDIA Corporation'
    device     = 'GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M]'
    class      = display
    subclass   = 3D
`
(Optimus system)

**Comment by mattmacy** [comment]
This is a known (duplicate) issue. I don't have Atom hardware at the moment. The problem is even more severe on Cherry Trail. I'm getting a "Tronsmart Ara X5 Windows 10 TV Box Cherry Trail Z8300 Quad Core" and am hoping that fixing that will fix this.

**Comment by mattmacy** [comment]
Actually I'm just going to mark this one as a duplicate since the other one has more information. Please tack on your device info there (#6).
