### ISSUE TITLE
Can we support Intel HD515？

### ISSUE THREAD

**Issue by ykla** [FreeBSDDesktop/freebsd-base-graphics#150]
Rt.Can we support Intel HD515？

**Comment by nomadlogic** [comment]
HD515 graphics *should* be supported on drm-next. I believe this GPU is found on Skylake CPU's (although my skylake has a HD530 which works great).  Give it a spin and let us know how it goes.

**Comment by ykla** [comment]
Yes,it'works,but how can I Adjust the screen brightness?

**Comment by valpackett** [comment]
It depends. There's [intel-backlight](https://www.freshports.org/graphics/intel-backlight/) (not updated for Skylake it seems), `acpi_video` and different `acpi_` modules for different laptops. On Thinkpads, just load `acpi_ibm` and brightness keys work.

**Comment by ghost** [comment]
Brightness adjuments works with [this version of intel_backlight](https://github.com/FreeBSDDesktop/intel_backlight_fbsd).

At least here on Skylake HD520
