### ISSUE TITLE
buildkernel aborts with ktime error

### ISSUE THREAD

**Issue by markusalbertgraf** [FreeBSDDesktop/freebsd-base-graphics#157]
Hello,
thanks for your great work.
When I called make buildkernel today GENERIC, GENERIC-NODEBUG, GENERIC_DRM and GENERIC_DRM-NODEBUG all aborted with the following error:

```
/usr/src/sys/dev/drm/drm_irq.c:819:11: error: implicit declaration of function
      'ktime_mono_to_real' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                etime = ktime_mono_to_real(etime);
                        ^
/usr/src/sys/dev/drm/drm_irq.c:819:11: note: did you mean 'ktime_get_real'?                   
/usr/src/sys/compat/linuxkpi/common/include/linux/timekeeping.h:19:1: note: 'ktime_get_real'
      declared here
ktime_get_real(void)
^
/usr/src/sys/dev/drm/drm_irq.c:819:9: error: assigning to 'ktime_t' (aka 'union ktime') from  
      incompatible type 'int'
                etime = ktime_mono_to_real(etime);
```
git revert -n 57fe21f
Seems to have fixed this.

$ uname -a
FreeBSD 12.0-CURRENT FreeBSD 12.0-CURRENT #0 29914b15437(drm-next): Mon Jul 10 15:05:12 CEST 2017     root@yoda:/usr/obj/usr/src-drm-next/sys/GENERIC  amd64

$ sysctl hw.model
hw.model: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz

Thanx for getting my laptop to work with an external screen!!!!!
I wish I could code on that level.

Best regards

Markus

**Comment by markjdb** [comment]
The line number suggests that you're using a copy of drm_irq.c from before commit 57fe21f. Are you building from a clean tree?

**Comment by pewright-tronc** [comment]
Was going to mention the same, I just built/installed world this morning w/o issues:

```
$ uname -ar
FreeBSD runner 12.0-CURRENT FreeBSD 12.0-CURRENT #19 ff9c7fc1f1a9(drm-next)-dirty: Wed Jul 12 09:53:16 PDT 2017     pwright@runner:/usr/obj/usr/home/pwright/git/freebsd-base-graphics/sys/GENERIC  amd64
```

**Comment by markusalbertgraf** [comment]
The line numbers did irritate me.
Thanx! I will start over!

**Comment by markusalbertgraf** [comment]
I deleted src and cloned afresh. You were totally right.
What I do not understand though is how reverting the commit did fix the error....
Still learning...
