### ISSUE TITLE
RADV

### ISSUE THREAD

**Issue by PhilPotter** [FreeBSDDesktop/freebsd-base-graphics#162]
Just a question - is drm-next using a new enough amdgpu driver to take advantage of RADV if compiled from latest Mesa? And if yes, had anyone tried it and got working Vulkan on FreeBSD? I don't have hardware to take advantage in any case, but am planning my next setup/build and would like to put it together with FreeBSD in mind. Thanks.

**Comment by iotamudelta** [comment]
drm-next is currently on whatever Linux 4.9 contains. There is a 4.10 branch in the works. I don't know if that's yet sufficient for RADV or not. I don't believe anybody has tried, the amdgpu is now in a relatively good shape for daily driving but I would expect there to be some (probably fixable) issues for whoever tries first.

**Comment by PhilPotter** [comment]
Thanks.

**Comment by valpackett** [comment]
It works! I've played vkQuake with it! Also Dolphin and RPCS3.

- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220982
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221540
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222175
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222182

(or [my ports fork](https://github.com/myfreeweb/freebsd-ports-dank), which has everything integrated already)
