### ISSUE TITLE
Why is this deprecated?

### ISSUE THREAD

**Issue by Diegovsky** [FreeBSDDesktop/freebsd-base-graphics#177]
The [wiki](https://wiki.freebsd.org/Graphics#AMD_Graphics) mentioned an issue with the amd driver. What happened?

**Comment by grahamperrin** [comment]
Whilst I can not answer the AMD question, there's a deprecation notice in the wiki at: 

https://github.com/FreeBSDDesktop/DEPRECATED-freebsd-base-graphics/wiki#deprecation-notice

Also, please see: 

https://github.com/freebsd/drm-kmod

**Comment by Diegovsky** [comment]
Thanks :)
