### ISSUE TITLE
cftdisk_2016060605 - Screen corrupt

### ISSUE THREAD

**Issue by RodrigoCapa** [FreeBSDDesktop/freebsd-base-graphics#20]
Hello, thank you for the effort.

The screen shows a moving image like this:

![imag0177](https://cloud.githubusercontent.com/assets/19779554/15825198/122bbb90-2c03-11e6-956b-64e6bb2ab5d4.jpg)

The following report it's made from a PCBSD 11.0-CURRENTMAY2016 FreeBSD with UEFI disabled:

[notebookinfo.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/300589/notebookinfo.txt)

I'll keep testing.

Again, thank you,
Rodrigo

**Comment by mattmacy** [comment]
Could you please look at #17 ? It looks like the exact same problem to me. If so please merge your information in to it. 

Thanks in advance.

**Comment by dch** [comment]
see comments in #17

**Comment by RodrigoCapa** [comment]
The screen output it's different, in this case it's unreadable. In the next test I'll try to logon with a remote console and get the report.

**Comment by mattmacy** [comment]
Is that the console or X? If X are you using the latest X and ddx as per the guidelines in the wiki?

**Comment by RodrigoCapa** [comment]
That's console and it's alive.

**Comment by RodrigoCapa** [comment]
PCBSD June does the same, I guess that's what you expect, but in this occasion with the installation graphical interface. It's like there is some kind of horizontal offset.

**Comment by mattmacy** [comment]
It's a snapshot of the same code...
