### ISSUE TITLE
VT screen shift to right bottom with MacBookPro 2015

### ISSUE THREAD

**Issue by huanghwh** [FreeBSDDesktop/freebsd-base-graphics#22]
If add  kern.vt.fb.default_mode="1440x900" in /boot/loader.conf, exec "ls -l", command line prompt do NOT show, hiding in bottom:
![img_1695](https://cloud.githubusercontent.com/assets/4677347/15842532/50955218-2c8c-11e6-9c46-2ef29fe8d34a.JPG)

**Comment by mattmacy** [comment]
So does this only happen if you try to change the mode? If you want to change the mode that way you'll also need to change the origin.

**Comment by huanghwh** [comment]
Yes, only happen if  try to change the mode.
So how to change the origin?

**Comment by nomadlogic** [comment]
Closing issue since this is a year old without update.
