### ISSUE TITLE
External display issues (Skylake)

### ISSUE THREAD

**Issue by trombonehero** [FreeBSDDesktop/freebsd-base-graphics#25]
I just tried plugging my Skylake laptop into an external display with 71faa5b. The xrandr support now seems to work well: I can change the display geometries and work off of the two displays. Two issues:
1. the driver does not detect when I unplug from the external display (I need to manually deactivate it) and
2. there are two horizontal lines of artifacts on my internal display after I disconnect from the external display.

Other than that, it's a definite improvement!

**Comment by mattmacy** [comment]
In my testing it always detects hotplug events. However, the uevent handler doesn't actually do anything. What is the correct response to a hotplug removal? Is there some mechanism to notify X?

**Comment by trombonehero** [comment]
That's a good question... the xf86-video-intel driver as a "HotPlug" option which defaults to enabled, so it sounds like there should be some notification going on. I don't understand KMS, etc., well enough to speculate whether the broken link in the chain might be.

**Comment by mattmacy** [comment]
The driver gets the event, but until I know where to send it I can't do anything. I'm too backlogged behind more serious bugs to do the digging myself for a few weeks at least.

**Comment by trombonehero** [comment]
Very understandable: thanks very much for all of your work!

**Comment by trombonehero** [comment]
This issue was resolved at some point between the last message in the thread and a lecture a month or two ago where things "just worked". Sorry that I can't be more specific...
