### ISSUE TITLE
Problem on mode switch (Skylake)

### ISSUE THREAD

**Issue by trombonehero** [FreeBSDDesktop/freebsd-base-graphics#27]
After leaving my screen closed for awhile, X often fails to resume with an error such as this:

https://photos.google.com/share/AF1QipMABaQilHpyIqpOSY378icLKsO0n2S2F8oDnkf5gFYV1CABe3jyLaFka6WuDwTJ-g?key=bE5PLWJQNXZPcC14NFJ5YXFTWHZQOWhLSXRVTXNn

**Comment by trombonehero** [comment]
This is still happening as of 3986f37:

https://goo.gl/photos/PQmneAhoG3phVQKV7

https://goo.gl/photos/M9ermAzkGamxvBbf7

Interestingly, the error message at the console now mentions both iwm0 and drm2... does that make it an iwm or drm problem? Or both? :)

**Comment by mattmacy** [comment]
I haven't done anything with resume. Maybe ask @emc2?

**Comment by trombonehero** [comment]
So, just to be clear, when I say "resume", I don't mean "suspend and resume": that just doesn't work on this laptop. I'm referring to X coming back from a blank screen.

Also, I have recently noticed this happening in other contexts, such as switching desktops within my window manager or switching away from a full-screen application. I'm not sure if those additional details are helpful... I hope they are!

**Comment by mattmacy** [comment]
I'm not sure what the option is to enable modesetting. Google can answer that. 

I'm not sure how to diagnose the issues you are seeing apart from running the Intel GPU Tools test suite on your system. I haven't added the missing linux bits, but that should work soon ish.

**Comment by trombonehero** [comment]
For future Google searchers: the modesetting driver is automatically picked up when the Intel driver is not explicitly enabled. I just removed `/usr/local/etc/X11/xorg.conf.d/20-intel.conf` and now X uses the modesetting driver.

**Comment by trombonehero** [comment]
This was resolved some time ago amidst all of the active development.
