### ISSUE TITLE
Border artifacts on Haswell

### ISSUE THREAD

**Issue by mattmacy** [FreeBSDDesktop/freebsd-base-graphics#28]
![img_0323_720](https://cloud.githubusercontent.com/assets/14172449/16068481/0fe3d498-327b-11e6-9f08-3b379347dc4e.jpg)

It's easy to create corrupted borders

**Comment by kev009** [comment]
If I ran glxgears and moved a kde decorated window around I saw very similar borders on SB

**Comment by mattmacy** [comment]
It's always possible that one can do this on Linux too. I need to start doing apples to apples testing.

**Comment by nomadlogic** [comment]
I am having similar issues on my Haswell laptop.  Running mate - pretty much all text and many icons are missing or completely corrupted.  I enabled dev.drm.drm_debug=-1 which as expected generated heaps of logs but nothing obvious to my eyes.

FWIW - on the same hardware using the kernel and i915kms modules which are shipping with 11-ALPHA5 I am able to run mate w/o any corruption.  LMK if logs or anything of that nature will help debug this.

**Comment by mattmacy** [comment]
Focusing on getting igt to work.

**Comment by martincahil** [comment]
I have a similar issues on my Haswell desktop. I am using drm-next-4.7 branch kernel. If you know where the problem is occurred, tell me please. I am waiting for your answer. Thank you.

**Comment by mattmacy** [comment]
I don't know where the issue is. I believe there is some sort of memory update serialization issue - one update is starting before another has finished. 

I'm busy fixing more serious issues impacting amdgpu at the moment but I'm sure this is a problem there as well.

**Comment by martincahil** [comment]
Thank you for your answer. :)
