### ISSUE TITLE
Canvas corruption on Cherry Trail

### ISSUE THREAD

**Issue by mattmacy** [FreeBSDDesktop/freebsd-base-graphics#29]
![img_0322_720](https://cloud.githubusercontent.com/assets/14172449/16068499/3b51318e-327b-11e6-8eb6-fcf1fb2350e6.jpg)

Chrome canvas corrupt / unusable

**Comment by Juanitou** [comment]
Same issue with Bay Trail-M.

**Comment by mattmacy** [comment]
![img_0332](https://cloud.githubusercontent.com/assets/14172449/16240696/4090e59e-379f-11e6-905c-94e67e44a55f.JPG)

Works now provided you pass --disable-gpu
