### ISSUE TITLE
gears strange behavior with MacBookPro 2015

### ISSUE THREAD

**Issue by huanghwh** [FreeBSDDesktop/freebsd-base-graphics#30]
While running gears, move mouse, gears look fast:
217 frames in  5.003 seconds = 43.374 FPS
311 frames in  5.016 seconds = 62.002 FPS
311 frames in  5.020 seconds = 61.952 FPS
255 frames in  5.212 seconds = 48.926 FPS

If stop moving mouse, gears look very slow:
29 frames in  5.053 seconds =  5.739 FPS
23 frames in  5.530 seconds =  4.159 FPS
19 frames in  5.004 seconds =  3.797 FPS
26 frames in  5.006 seconds =  5.194 FPS

**Comment by mattmacy** [comment]
Is this with the latest sources? I just fixed this issue on Cherry Trail a few days ago.

**Comment by huanghwh** [comment]
Not latest, I will update to the latest soon.

**Comment by kev009** [comment]
This was fixed for me in lastest

**Comment by huanghwh** [comment]
Yes! The latest version fixed this problem, thanks!
