### ISSUE TITLE
System lock under MacBookPro 2015

### ISSUE THREAD

**Issue by huanghwh** [FreeBSDDesktop/freebsd-base-graphics#32]
FreeBSD mbp.gddsn.org.cn 11.0-ALPHA1 FreeBSD 11.0-ALPHA1 #12 fc26d6b(drm-next-4.6)-dirty: Thu Jun 16 06:17:18 CST 2016     root@mbp.gddsn.org.cn:/usr/obj/home/hwh/git/freebsd-base-graphics/sys/MACBOOK  amd64

Sometime system lock:
![img_1764](https://cloud.githubusercontent.com/assets/4677347/16138988/b8ee1da4-3475-11e6-905d-fd1a7976fb14.JPG)

**Comment by mattmacy** [comment]
Please up date to the latest sources which will allow you to get a backtrace and probably a core and set skip_ddb in your loader.conf as described in the wiki.

**Comment by huanghwh** [comment]
Ok, I will try to get a backtrace...

**Comment by mattmacy** [comment]
I _just_ committed another possible fix too. So might want to pull again.

**Comment by huanghwh** [comment]
Ok...

**Comment by huanghwh** [comment]
I can't reproduce it with the latest version 0f32ed3.
