### ISSUE TITLE
Artifacts on MacBookPro 2015 again

### ISSUE THREAD

**Issue by huanghwh** [FreeBSDDesktop/freebsd-base-graphics#34]
Update to the latest, Got artifacts again. About week ago, no this problem.
![img_1785](https://cloud.githubusercontent.com/assets/4677347/16164645/f08c97a8-3511-11e6-9c6a-978e0f527ce0.JPG)

**Comment by mattmacy** [comment]
Are you running the latest xf86-video-intel per the wiki?

**Comment by huanghwh** [comment]
No, I am running xf86-video-intel from ports.

**Comment by mattmacy** [comment]
That's 3 or 4 years old. You need to either build newer from the xserver-next branch in:
https://github.com/freebsd/freebsd-ports-graphics

I've built a bunch of up to date packages here:
http://www.bsddesktop.com/images/xserver-next-pkgs/

**Comment by huanghwh** [comment]
After update to xserver-next-pkgs, got this error:
![img_1787](https://cloud.githubusercontent.com/assets/4677347/16166114/e6725d12-351a-11e6-947e-e9a6c38acd21.JPG)

**Comment by mattmacy** [comment]
maybe you can bisect back to the change that introduced artifacts?

**Comment by huanghwh** [comment]
The version "fc26d6b" is good, and the version "ac46418" introduced artifacts.

**Comment by mattmacy** [comment]
Thanks.

**Comment by mattmacy** [comment]
https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/1dd30c600a765c60e59e9caebb36677ecb192ff3 should add  a new tunable / sysctl for you to disable write combining mmap. I'm not reverting the code because it _should_ work and I want to understand why it causes problems. But this knob will allow you to turn it off.

**Comment by huanghwh** [comment]
I should be mentioned that I still use xf86-video-intel from ports as  xf86-video-intel from xserver-next-pkgs caused GPU hang.
I  set dev.drm.skipwc=1, still got this, artifacts in menu item:
![img_1798](https://cloud.githubusercontent.com/assets/4677347/16184427/d87470da-36ee-11e6-8040-8b86f4dab07e.JPG)

**Comment by mattmacy** [comment]
Please let me know how the latest changes behave for you. They fix artifacts on some systems.

**Comment by mattmacy** [comment]
On second thought I should probably not have committed so soon.

**Comment by huanghwh** [comment]
Unfortunately, with  4059f9b, still got the artifacts in the mate system menu item.

**Comment by mattmacy** [comment]
I've disabled the MMAP_WC change for now. Does it bring it back to normal for you?

**Comment by huanghwh** [comment]
No，with ecd31fb still got the artifacts in the mate system menu item.

**Comment by mattmacy** [comment]
Then that change must not have introduced the artifacts. Can you check again?

**Comment by huanghwh** [comment]
OK, I will double-check it soon...

**Comment by huanghwh** [comment]
I had checked again,same result:
![image](https://cloud.githubusercontent.com/assets/4677347/16287700/b1879966-3941-11e6-8210-698787e6aa41.jpeg)
![image](https://cloud.githubusercontent.com/assets/4677347/16287701/b24d3f04-3941-11e6-8755-1a5dc109efc7.jpeg)

**Comment by huanghwh** [comment]
The artifacts is gone after I disable these code: 

/*
        if (args->flags & ~(I915_MMAP_WC)) {
                DRM_DEBUG("Attempting to mmap with flag other than WC set\n");
                return -EINVAL;
        }
        if (args->flags & I915_MMAP_WC && !cpu_has_pat) {
                DRM_DEBUG("Attempting to mmap WC without pat\n");
                return -ENODEV;
        }
*/

**Comment by huanghwh** [comment]
"de6c000" fixed my problem.
