### ISSUE TITLE
sound & video playback at half speed

### ISSUE THREAD

**Issue by dch** [FreeBSDDesktop/freebsd-base-graphics#36]
present on:
-  Intel NUC5i5RYH
- Apple MacBook Pro 15" retina mid 2014 model
- affects mp3 via /dev/dsp\* and via vlc, chromium, or firefox
# xorg/intel.conf

Section "Device"
    Identifier  "Card0"
    # Driver        "scfb"
    Driver      "intel"
    Option      "AccelMethod" "sna"
EndSection

MBP logs:
dmesg: https://dpaste.de/nvNc
xorg: https://dpaste.de/nkyN

**Comment by mattmacy** [comment]
Are you using GENERIC? No one else is seeing half speed playback.

**Comment by neelchauhan** [comment]
On my laptop (Dell Inspiron 7352, Broadwell i7 5500U), the video lags or even freezes but the audio does not (or it may, but a little if it does). This was tested on Firefox.

I might just have to stick with Linux on this laptop (Linux works excellently on this laptop, where *BSD support isn't too great as I also tried OpenBSD).

**Comment by mattmacy** [comment]
@neelchauhan have you tried disabling video acceleration? At least with chrome this is off by default on most Linux distros. This is really a ports bug.

**Comment by mattmacy** [comment]
@neelchauhan It turns out I see the same issue on Firefox. And I've actually noticed as well that FF doesn't get vblank interrupts on WebGL demos. I didn't realize FF had issues because I'm really not at all fond of it. If you can bare to use chrome/chromium (port calls itself chromium but the executable gets named chrome ... go figured), it works like a champ. If you have to use FF then Linux is probably the best route for you. 

Nonetheless, I will fix this eventually.

**Comment by mattmacy** [comment]
@dch If you're seeing this with mp3 playback it is definitely not a graphics driver bug. Are you running powerd? Have you tried disabling that?

**Comment by mattmacy** [comment]
@dch let's see your rc.conf and loader.conf

**Comment by dch** [comment]
OK I literally just finished rebuilding All The Things using Monday 27th June and we're better off:
- Using scfb sound & video are flawless
- Under i915kms sound is flawless but video is choppy, although correct speed
- src: a76e358ece4cace0e0723689ff5ab10522eda099 (+ cherrypicked BZ210382)
- ports: a166b9743d29a803f7af49c31d6478cc9c889574
- config:https://gist.github.com/dch/69249936bec2cdcd0a20421640902bb0 has config incl Xorg  /usr/local/etc/X11/xorg.conf.d/*
- both browsers have choppy video, but VLC with hw acceleration enabled works fine

Just retrying all of this without mains power in case powerd is the root cause & I'll jump on IRC

**Comment by mattmacy** [comment]
If you're not having problems on scfb, but are on i195kms that means you need to turn off video acceleration. On ubuntu on a gtx980ti chrome disables hw video acceleration. The FreeBSD default to always use it clearly isn't correct.

**Comment by dch** [comment]
thanks @mattmacy is this disabling it in xorg.conf.d just by excluding the `AccelMethod`, or does it require something like disabling Chrome's `Use hardware acceleration when required`?

```
Section "Device"
    Identifier  "Card0"
    Driver      "scfb"
    # Driver        "intel"
    # Option        "AccelMethod" "sna"
EndSection
```

FWIW powerd made no difference to results.

**Comment by mattmacy** [comment]
That disables the driver altogether. On chromium: --disable-accelerated-video-decode

**Comment by mattmacy** [comment]
Are you running a debug kernel? If so is driver offloaded playback still choppy on a non-debug kernel?

**Comment by dch** [comment]
I re-tested this today on the NUC with drm-next and xserver-next, using youtube Queen videos.
- when sound is coming out headphone hack, then all is perfect (mpg123 for mp3, firefox/chrome for video speed <also in sync)
- switch sound to HDMI output, restart browsers & play youtube video again or mpg123 mp3, and it's all 1/2 speed again

I've fiddled with powerd and can't seem to find a difference, theres nothing in the system BIOS config that tells me anything of use either, although I boot via UEFI.

**Comment by dch** [comment]
I updated firmware on the NUC this week, rebuilt drm-next and issue is still present... weird. I'm now wondering whether this is related to the display, hope to get my hands on one next week to test against. Additional ideas welcomed!

**Comment by dch** [comment]
Did some cross testing:

- [dell](http://accessories.ap.dell.com/sna/productdetail.aspx?c=sg&cs=sgdhs1&l=en&s=dhs&sku=210-ADTB&redirect=1) monitor
- same issues as asus projector & hk amp output originally reported
- ubuntu 16.10 (default 4.8.x kernel) has no issues; I grabbed [edid output](https://gist.github.com/dch/0a873886cc164e9244edb73ad8180990)

I've been doing some reading trying to understand how this "stuff" works - slow progress. It seems HDMI sound speed is calculated automatically using Pixel Clocks.. further surfing lead me to these two:

- https://bugs.freedesktop.org/show_bug.cgi?id=75038
- https://bugs.freedesktop.org/show_bug.cgi?id=97442#c25

The last one looks like a smoking gun and the diffs are quite localised so I will have a crack at patching them & report back.

**Comment by nomadlogic** [comment]
Are you still running into this issue @dch ? I've been able to watch video without issues using drm-next for quite a while now.

**Comment by neelchauhan** [comment]
On a HP EliteBook 9470m I use for purely 'personal' computing with the `graphics/drm-next-kmod` port, I do not have this issue. I do not run FreeBSD on the Inspiron I mentioned earlier (my Dell mostly runs Ubuntu now).

**Comment by dch** [comment]
coming back to this bug ~ 6 years later, it's nothing to do with drm-kmod, something to do with this specific NUC hardware. Note that under Linux the issue is addressed.
