### ISSUE TITLE
mate/marco  coredump  with  drm-4.6-next

### ISSUE THREAD

**Issue by huanghwh** [FreeBSDDesktop/freebsd-base-graphics#37]
I am using cftdisk_nodebug_2016062423.img under MacBookPro 2015.
Try to use  mate desktop, when  I select TraditionalOK/Green, marco coredump:
VT: Replacing driver "efifb" with new "fb".
start FB_INFO:
type=11 height=1800 width=2880 depth=32
cmsize=16 size=21196800
pbase=0x90000000 vbase=0xffffffff82410000
name=drmn0 flags=0x0 stride=11776 bpp=32
cmap[0]=0 cmap[1]=7f0000 cmap[2]=7f00 cmap[3]=c4a000
end FB_INFO
drmn0: fb0: inteldrmfb frame buffer device
[drm:0xffffffff838d8f95s] _ERROR_ uncleared fifo underrun on pipe A
[drm:0xffffffff838897e5s] _ERROR_ CPU pipe A FIFO underrun
pid 934 (marco), uid 1001: exited on signal 6 (core dumped)
pid 985 (marco), uid 1001: exited on signal 6 (core dumped)
pid 987 (marco), uid 1001: exited on signal 6 (core dumped)

**Comment by mattmacy** [comment]
Hrrm. What does sysct hw.model show for your Macbook?

**Comment by huanghwh** [comment]
% sysctl hw.model
hw.model: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz

**Comment by huanghwh** [comment]
And sometimes got error like this:
https://cloud.githubusercontent.com/assets/4677347/16166114/e6725d12-351a-11e6-947e-e9a6c38acd21.JPG

**Comment by mattmacy** [comment]
Yup. I need to add debugfs support to see what is going wrong when the ring hangs. Personally I haven't seen the blitter ring hang, only the render ring.

**Comment by mattmacy** [comment]
How do you run it in your .xinitrc? I don't see any problems with just running: exec /usr/local/bin/mate-session

**Comment by huanghwh** [comment]
Do you select the theme "TraditionalOK" in mate-appearance-properties?
Only one line exec mate-session in my .xinitrc.

**Comment by nomadlogic** [comment]
Howdy, is this still an open issue on your end?  Otherwise we'll close this out.
