### ISSUE TITLE
Very Slow Keyboard Input On Haswell

### ISSUE THREAD

**Issue by nomadlogic** [FreeBSDDesktop/freebsd-base-graphics#39]
$ sysctl hw.model
hw.model: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
$ uname -a
FreeBSD pier 11.0-ALPHA5 FreeBSD 11.0-ALPHA5 #6 a76e358(drm-next-4.6)-dirty: Fri Jul  1 20:09:29 PDT 2016     root@srd0009:/usr/obj/usr/home/pwright/git/freebsd-base-graphics/sys/GENERIC  amd64

When I load the i915kms module on this platform I get very slow keyboard input.  The system is usable, but it takes several seconds for keyboard touches to update on the console.  When I startx (doing "Xorg -configure") and then exit X keyboard inputs update as expected.

**Comment by mattmacy** [comment]
Does this not happen on HEAD? This does not strike me as a video driver issue, more likely a vt_fb issue.

**Comment by nomadlogic** [comment]
So I am running the kernel and modules that ship with 11-ALPHA5 and am not seeing this behavior.  I am going to do some more testing on my end and see if i can help debug this.

**Comment by nomadlogic** [comment]
i can't reproduce - your first assumption about this being a vt_fb issue is most likely correct.
