### ISSUE TITLE
QT5 redraw problems

### ISSUE THREAD

**Issue by mattmacy** [FreeBSDDesktop/freebsd-base-graphics#40]
![img_0337](https://cloud.githubusercontent.com/assets/14172449/16571234/ed852e64-420c-11e6-89d1-fe2348dce1bb.JPG)

When a qt5 window is partially covered it doesn't get redrawn when revealed.

**Comment by pkgdemon** [comment]
Just for reference I found that disabling my internal laptop display, and switching to HDMI only makes the symptons go away.  

```
Section "Module"
        Load  "extmod"
        Load  "record"
        Load  "dbe"
        Load  "glx"
        Load  "dri"
        Load  "dri2"
EndSection


Section "Device"
        Identifier      "Card0"
        Driver          "intel"
        Option "monitor-LVDS-1" "LVDS-1"
EndSection

Section "Monitor"
Identifier "Configured Montior"
EndSection

Section "Monitor"
Identifier "LVDS-1"
Option "Disable" "true"
EndSection

Section "Screen"
Identifier "Default Screen"
Monitor "Configured Monitor"
Device "Configured Video Device"
EndSection
```

**Comment by pkgdemon** [comment]
The other option with LVDS-1 on has been to turn off acceleration.

```
Section "Device"
        Identifier      "Card0"
        Driver          "intel"
Option          "AccelMethod"               "none"
EndSection
```

**Comment by pkgdemon** [comment]
This problem is not caused by LVDS alone.  It is triggered by a card having multiple outputs.  To test this theory on another affected system I printed out available outputs by running `xrandr1`, and the proceeded to disable the outputs in `/etc/x11/xorg.conf`.

```
Section "Module"
        Load  "extmod"
        Load  "record"
        Load  "dbe"
        Load  "glx"
        Load  "dri"
        Load  "dri2"
EndSection


Section "Device"
        Identifier      "Card0"
        Driver          "intel"
        Option "monitor-DP-1" "DP-1"
        Option "monitor-DP-2" "DP-2"
        Option "monitor-HDMI-1" "HDMI-1"
        Option "monitor-VIRTUAL-1" "VIRTUAL-1"

EndSection

Section "Monitor"
        Identifier "DP-1"
        Option "Disable" "true"
EndSection

Section "Monitor"
        Identifier "DP-2"
        Option "Disable" "true"
EndSection 

Section "Monitor"
    Identifier "HDMI-1"
    Option "Disable" "true"
EndSection

Section "Monitor"
        Identifier "Configured Montior"
EndSection

Section "Monitor"
        Identifier "VIRTUAL-1"
        Option "Disable" "true"
EndSection

Section "Screen"
    Identifier "Default Screen"
    Monitor "Configured Monitor"
    Device "Configured Video Device"
EndSection
```

As a result after disabling the additional outputs everything works perfectly.

**Comment by TypedLambda** [comment]
I get the same problems on my Thinkpad T460p and a Clevo Barebone. I'll try the "workaround" but I actually use a external monitor with the thinkpad...

**Comment by mattmacy** [comment]
@TypedLambda can you tell me what happens if you use drm-next?

**Comment by TypedLambda** [comment]
It happens on a recent trueos desktop install which is using drm-next as far as i know. Both systems are currently installing trueos desktop, the unstable branch. I'll retest when both systems are done.
It happens with UXA and SNA acceleration, (tested  on my Clevo). And it only seems to affect QT applications.

**Comment by mattmacy** [comment]
They're currently using drm-next-4.7 - nonetheless, hold off on drm-next until next week. There are a bunch of regressions that need fixing.
