### ISSUE TITLE
xorg kernel panic, i915_driver_load, Ergo Vista 621 notebook

### ISSUE THREAD

**Issue by grahamperrin** [FreeBSDDesktop/freebsd-base-graphics#41]
Ergo Vista 621 with Intel GM45 GPU. 

PC-BSD 11.0-CURRENTMAY2016 is OK. 

PC-BSD 11.0-CURRENTJUNE2016 works when limited to VESA but seems to panic with any attempt to use i915. 

(I can not get a core dump, but I do have photographs showing i915_driver_load… in each backtrace. If/when I get the photographs off my phone, I'll add them to this issue.)

**Comment by grahamperrin** [comment]
![tmp_25655-img_20160705_071416-1049070813](https://cloud.githubusercontent.com/assets/192271/16595709/8092df54-42e8-11e6-80d6-b32e015c88c6.jpg)

![tmp_25655-img_20160705_185040-491746212](https://cloud.githubusercontent.com/assets/192271/16595728/99353ef8-42e8-11e6-9121-e0f36754981a.jpg)

**Comment by mattmacy** [comment]
Known problem in pre Sandy Bridge with the update. Mostly fixed in drm-next-4.6 as of yesterday. Try updating from these sources.

**Comment by grahamperrin** [comment]
Thanks. 

I don't yet know whether the update routine that's traditional for PC-BSD CURRENT will allow an update to forthcoming 11.0-CURRENTJULY2016, I'll do what I can.

**Comment by grahamperrin** [comment]
With the operating system installed from 
TrueOS-Desktop-11.0-CURRENTJULY2016-07-12-2016-x64-USB.img 
there is no longer a kernel panic. 

Thanks to the developers!
