### ISSUE TITLE
Page fault in `linux_queue_work` when loading `i915kms`

### ISSUE THREAD

**Issue by trombonehero** [FreeBSDDesktop/freebsd-base-graphics#43]
Running c132a99 + recent `-CURRENT`, I get a page fault every time I `kldload i915kms`. I've created a [gist of my core.txt file](https://gist.github.com/trombonehero/d0732c268318c23c520a1dfd09696808) and am rebuilding vanilla c132a99 to ensure that the merge wasn't somehow to blame. Please let me know if there's any other information that would be helpful...

**Comment by trombonehero** [comment]
I should probably mention the hardware I'm using:

```
vgapci0@pci0:0:2:0:     class=0x030000 card=0x1cfd1043 chip=0x191e8086 rev=0x07 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'HD Graphics 515'
    class      = display
    subclass   = VGA
```

**Comment by mattmacy** [comment]
Can you retry with just drm-next-4.6? I can't really support arbitrary merges.

**Comment by trombonehero** [comment]
That's fair enough. Using vanilla drm-next-4.6 (c132a99), it looks like the problem doesn't occur. Sorry for the noise.

I suppose the real outcome of this issue report is that "something happened recently in -CURRENT that has interactions with drm-next-4.6"... hopefully this won't cause too much trouble the next time you merge -CURRENT (or, hopefully, when you merge drm-next-4.6 into 12-CURRENT!).

**Comment by mattmacy** [comment]
I hit this when trying to update https://reviews.freebsd.org/D7042 broke callout_drain.

Thanks.
