### ISSUE TITLE
Visual artifacts in Thunderbird (GTK2?)

### ISSUE THREAD

**Issue by trombonehero** [FreeBSDDesktop/freebsd-base-graphics#52]
Some messages in Thunderbird exhibit an odd set of artifacts:
![screenshot_2016-07-15_17-12-13](https://cloud.githubusercontent.com/assets/85833/16887637/e2af14a8-4ab5-11e6-8294-13bf0163b49a.png)

This is with `freebsd-base-graphics` 3986f37 and Xorg ports from `xserver-next`.

**Comment by mattmacy** [comment]
Is this a recent regression?

**Comment by trombonehero** [comment]
(also, I should probably say that I'm using SNA acceleration... with UXA, basically the whole screen looks like this)

**Comment by mattmacy** [comment]
can you try modesetting instead of SNA?

**Comment by trombonehero** [comment]
I'm not sure if it's a regression: I only recently got the `xserver-next` parts working. I can try modesetting... is it just `"AccelMethod" "modesetting"` in the relevant `xorg.conf.d` file?

**Comment by trombonehero** [comment]
Ok, it seems that the modesetting driver automatically gets picked up when I remove the file with `Driver "intel"` from /usr/local/etc/X11/xorg.conf.d. So far, so good... closing for now, as I can always re-open the issue if I see the artifacts again.
