### ISSUE TITLE
Where'd my 'm's go?

### ISSUE THREAD

**Issue by mattmacy** [FreeBSDDesktop/freebsd-base-graphics#56]
![img_0341](https://cloud.githubusercontent.com/assets/14172449/17201800/c9ee18fc-5446-11e6-8606-16becb78722a.JPG)

**Comment by nomadlogic** [comment]
lol - ran into this issue as well in xfce4 last night on my skylake system.  IIRC i switched the modesetting driver back to the intel driver in xorg which seemed to fix things up.

**Comment by mattmacy** [comment]
This was with uxa and was transient

**Comment by valpackett** [comment]
is UXA even supposed to work on modern hardware?

several months ago, when `drm-i915-update-38` was new and I just installed it on my haswell thinkpad, UXA was corrupting all the text, SNA worked fine (and still does)

**Comment by mattmacy** [comment]
Have not seen again.
