### ISSUE TITLE
Control-Alt-F1 and Control-Alt-F2 no longer work

### ISSUE THREAD

**Issue by grahamperrin** [FreeBSDDesktop/freebsd-base-graphics#61]
TrueOS-Desktop-12.0-CURRENT-08-01-2016-x64-USB.img installed to an Ergo Vista 621 notebook. 

From https://github.com/trueos/trueos-core/issues/13: 

**Expected**

System console (ttyv0), first virtual console (ttyv1).

**Actual results**

A very dark grey full screen with a momentary quarter screen of flashing colours (predominantly blue and red, as far as I can tell), then a non-blinking mid-grey underscore cursor on the very dark grey background.

In some cases there's no cursor.

Control-Alt-F9 returns me to the GUI that's severely bugged by https://github.com/trueos/trueos-core/issues/19.

… 

Issue with the DRM stack and using intel. …

**Comment by mattmacy** [comment]
This is a KMS bug, but TrueOS should probably just be auto-configuring scfb for your system.

@dumbbell can maybe comment

**Comment by grahamperrin** [comment]
> … TrueOS should probably just be auto-configuring scfb for your system. … 

For what it's worth, this notebook previously used intel-3d-enable without difficulty. The same notebook featured in https://github.com/freebsd/freebsd-base-graphics/issues/9

**Comment by mattmacy** [comment]
> For what it's worth, this notebook previously used intel-3d-enable without difficulty. The same notebook featured in freebsd#9 

I'm sure it did. However, it didn't support UHD out, Kaby Lake, Skylake, Broadwell, or half a dozen Haswell models. The initial KMS work for Ivy Bridge was done without any thought given to maintainability. So this work is largely a fresh start. That is why it took several years just to get a partial Haswell update.

Pre-SB hardware relies on the AGP code which doesn't mesh cleanly with the updated DRM code but is too old to justify a corresponding refresh. I'm hoping that @dumbbell can address your issues eventually.

**Comment by grahamperrin** [comment]
Thanks – and I hope that my earlier comment wasn't misconstrued as pushy. 

(I have seen SCFB in use, but I have not _yet_ got my head around modesetting and other recent developments in/around TrueOS Desktop. All very new to me.)

**Comment by nomadlogic** [comment]
I've actually used scfb quite a bit on a skylake system.  video playback was not the best, but it was certainly usable for daily work uses (web browser + bunch of shells).  I did the following to use it:

$ pkg install xf86-video-scfb

Then configured my "Device" section of /etc/X11/xorg.conf like so:

```
Section "Device"
        Identifier  "Card0"
        Driver      "scfb"
EndSection

```

Hope this helps.

**Comment by grahamperrin** [comment]
With an installation of TrueOS Desktop that was performed on 2016-08-11, this bug is no longer reproducible.
