### ISSUE TITLE
Opening GTK3 file selection dialog causes applications to crash

### ISSUE THREAD

**Issue by ristoe** [FreeBSDDesktop/freebsd-base-graphics#63]
- GTK3 applications crash when opening file selection dialog (used when trying to save or open file in application)
  - There is issue with certain GTK2 applications (like `x11-fm/pcmanfm`, which crashes when navigating to certain directories)
- There also seems to be issue with image viewers (such as `graphics/geeqie`) with crashes when navigating to certain files
- Firefox compiled with GTK3 also crashed when opening file selection dialog, when I recompiled firefox with GTK2 crashes stopped.
- I suspect it has something to do with generating file previews in file selection dialog.

While trying to debug the issue I discovered that debugging actually fixed the issue (until Xorg is shutdown/started again):
#### Run 1

```
$ zenity --file-selection
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:1029): Gdk-WARNING **: zenity: Fatal IO error 35 (Resource temporarily unavailable) on X server :0.0.
```
#### Run 2

```
$ zenity --file-selection
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:1034): Gdk-ERROR **: The program 'zenity' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadRequest (invalid request code or no such operation)'.
  (Details: serial 374 error_code 1 request_code 0 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/BPT trap (core dumped)
```

Repeating `zenity --file-selection` command alternates results between run 1 and run 2
#### Run 3

No crash, just completely black window, interrupted with Ctrl-C

```
$ env GDK_SYNCHRONIZE=1 zenity --file-selection
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
load: 0.33  cmd: zenity 1039 [select] 4.64r 0.31u 0.04s 2% 68440k
load: 0.31  cmd: zenity 1039 [select] 5.79r 0.31u 0.04s 1% 68440k
load: 0.31  cmd: zenity 1039 [select] 7.11r 0.31u 0.04s 1% 68472k
^C
```
#### Run 4

File selection window opens up, no issues navigating directory tree etc. Works as it should.

```
$ truss env GDK_SYNCHRONIZE=1 zenity --file-selection
(truss output omitted)
```
#### Run 5

Running zenity without GDK_SYNCHRONIZE and without truss again and result is the same as run#4.

```
$ zenity --file-selection
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

Subsequent `zenity --file-selection` calls work normally. Using geeqie to view images/galleries works without issues too. The run sequence described works every time and I use it as a temporary workaround.

`uname -a`:

```
FreeBSD desktop.dh 11.0-BETA3 FreeBSD 11.0-BETA3 #0: Sat Aug  6 18:09:58 EEST 2016     root@desktop.dh:/usr/obj/usr/drm-next-4.6-11-STABLE/sys/SKYLAKE-DESKTOP-NODEBUG  amd64
```

`sysctl hw.model`:

```
hw.model: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
```

All ports are compiled from [xserver-next ports tree](https://github.com/freebsd/freebsd-ports-graphics/tree/xserver-next) (commit `9adce7e4635561b813c818156fcfaa389b441b85`)

**Comment by ristoe** [comment]
Upgraded to `drm-next-4.6` branch, still experiencing same issue (but the workaround still applies)

```
FreeBSD desktop.dh 12.0-CURRENT FreeBSD 12.0-CURRENT #0 3a8ce37(drm-next-4.6): Sun Aug 14 20:01:04 EEST 2016     root@desktop.dh:/usr/obj/usr/drm-next-4.6/sys/GENERIC  amd64
```

**Comment by mattmacy** [comment]
The 4.6 branch is not the latest and does not have the tag he was referring to.

**Comment by mattmacy** [comment]
Please try drm-next.

**Comment by ristoe** [comment]
Upgrading to drm-next didn't help, but I fiddled with various GTK and GDK envirnoment variables found that by setting `GDK_RENDERING` to `image` GTK3 file selection dialogs don't cause issues (default value is `similar`).

For example: `env GDK_RENDERING=image zenity --file-selection`

More info on GDK/GTK envirnoment variables: https://developer.gnome.org/gtk3/stable/gtk-running.html#GDK-Debug-Options

**Comment by valpackett** [comment]
"This essentially turns off all hardware acceleration inside GTK" doesn't sound good, but it fixed the black dialogs for me

**Comment by johalun** [comment]
Is GDK_RENDERING synonym to cairo surface backend in this case? If so, does it make any difference compiling cairo with GL or GLESv2 backend? (probably not, just winging it)

**Comment by valpackett** [comment]
It does! Just rebuilt cairo with GLES, the file dialog works!

**Comment by johalun** [comment]
Wow, amazing :)

**Comment by hselasky** [comment]
Closing this issue. Looks solved.
