### ISSUE TITLE
Blank screen on Broadwell with drm-v4.7-final

### ISSUE THREAD

**Issue by felix** [FreeBSDDesktop/freebsd-base-graphics#72]
Running 12-CURRENT world with a kernel from drm-v4.7-final I get a blank screen which requires a reboot. No xorg.conf so it defaults to SNA acceleration. As discussed on [mailing list](https://lists.freebsd.org/pipermail/freebsd-x11/2016-August/017838.html) Files attached.

[notebookstats.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/425063/notebookstats.txt)
[procstat.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/425064/procstat.txt)
[messages.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/425075/messages.txt)

**Comment by felix** [comment]
An update on this, running the same laptop with monitor attached via HDMI, X loads but only on the external monitor. The laptop display is still blank.

**Comment by grahamperrin** [comment]
Is the blank display a sort of part-lit grey?

**Comment by felix** [comment]
Not really grey. I can tell that the backlight is on but it is still black.

**Comment by grahamperrin** [comment]
OK. I follow this issue with interest as I have comparable symptoms (not necessarily the same bug) with TrueOS Desktop on a Broadwell HP EliteBook 850 G2 notebook. From HP's page for the product: "Intel® Core™ i7-5500U with Intel HD Graphics 5500 (2.4 GHz, up to 3 GHz with Intel Turbo Boost Technology, 4 MB cache, 2 cores)" and a discrete "AMD Radeon™ R7 M260X (1 GB DDR5 dedicated, dual graphics)". At home I use it with an external display on VGA; at work, in a dock with two externals, each on DisplayPort, extended desktop.

**Comment by felix** [comment]
Using bf19cef I no longer experience this. Not sure when it was fixed for me though.
