### ISSUE TITLE
Radeon HD 8210 -> drm-next 4.6/4.7 ?

### ISSUE THREAD

**Issue by linuxcompitech** [FreeBSDDesktop/freebsd-base-graphics#74]
Hi,

does drm-next 4.6 or 4.7 with an AMD Radeon HD 8210 GPU ( Sea Islands ) work?

VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Kabini [Radeon HD 8210]

**Comment by iotamudelta** [comment]
Currently, amdgpu and radeon KMS are both rather untested. Your GPU should be supported by both radeon and amdgpu, AFAIK. The amdgpu module will be fixed up first, I am certain @mattmacy will issue another CFT on the mailing lists once that is done.

**Comment by mattmacy** [comment]
This is WIP dependent on further ports work. Talk to Koop Mast.
