### ISSUE TITLE
firmware(9) warnings are confusing

### ISSUE THREAD

**Issue by linuxcompitech** [FreeBSDDesktop/freebsd-base-graphics#75]
I tried to copy radeon-ucode to /lib/firmware/radeon but it doesn't work.

Can you tell me, how does the kernel where to look for driver firmware?
`
[drm:cik_init_microcode] 
[drm] Loading kabini Microcode
radeon/kabini_pfp.bin: could not load firmware image, error 2
radeon/kabini_pfp.bin: could not load firmware image, error 2
radeon/kabini_me.bin: could not load firmware image, error 2
radeon/kabini_me.bin: could not load firmware image, error 2
radeon/kabini_ce.bin: could not load firmware image, error 2
radeon/kabini_ce.bin: could not load firmware image, error 2
radeon/kabini_mec.bin: could not load firmware image, error 2
radeon/kabini_mec.bin: could not load firmware image, error 2
radeon/kabini_rlc.bin: could not load firmware image, error 2
radeon/kabini_rlc.bin: could not load firmware image, error 2
radeon/kabini_sdma.bin: could not load firmware image, error 2
radeon/kabini_sdma.bin: could not load firmware image, error 2
[drm] Internal thermal controller without fan control
[drm] radeon: dpm initialized
radeon/BONAIRE_uvd.bin: could not load firmware image, error 2
radeon/BONAIRE_uvd.bin: could not load firmware image, error 2
drmn0: failed to load firmware image radeon_BONAIRE_uvd_bin
drmn0: radeon_uvd: Can't load firmware "radeon/BONAIRE_uvd.bin"
radeon/BONAIRE_vce.bin: could not load firmware image, error 2
radeon/BONAIRE_vce.bin: could not load firmware image, error 2
drmn0: failed to load firmware image radeon_BONAIRE_vce_bin
drmn0: radeon_vce: Can't load firmware "radeon/BONAIRE_vce.bin"
`

Frank

**Comment by mattmacy** [comment]
The firmware is built in to kernel modules. The complaints you're seeing are essentially a bug in the firmware API. The driver will panic if firmware doesn't load.

**Comment by mattmacy** [comment]
Should be fixed in drm-next
