### ISSUE TITLE
libreoffice causes Xorg to crash

### ISSUE THREAD

**Issue by lattera** [FreeBSDDesktop/freebsd-base-graphics#78]
On drm-next-4.7, opening a document in libreoffice causes Xorg to crash.

Here's what's in my `dmesg` when the crash happens:

```
[68465] WARN_ON(!wm_changed)
[68465] hdacc1: Unexpected unsolicited response with tag 63: ffffffff
[68465] hdacc1: Unexpected unsolicited response with tag 63: ffffffff
[68465] WARN_ON(!wm_changed)
```

`uname -a` output: `FreeBSD shawn-work-laptop-hbsd 12.0-CURRENT-HBSD FreeBSD 12.0-CURRENT-HBSD #0: Tue Aug 30 22:57:44 UTC 2016     root@laptop-dev-02:/usr/obj/usr/src/sys/LATT-SEC  amd64`

I'm using the hardened/current/drm-next-4.7 branch in the HardenedBSD/hardenedBSD-playground repo. I'm at commit `d1507bd674e5ba4a67cc6edde1afac7b1ca352ea`.

**Comment by MegaManSec** [comment]
This happens in drm-next, too, using xserver-next ports:
FreeBSD user 12.0-CURRENT FreeBSD 12.0-CURRENT #0 476849d(drm-next): Thu Aug 25 04:30:56 AEST 2016     root@user:/usr/obj/usr/src/sys/GENERIC  amd64

from vt when startx cashes:

```
(EE) 
(EE) Backtrace:
(EE) 0: /usr/local/bin/X (OsInit+0x38a) [0x5aaf0a]
(EE) 1: /lib/libthr.so.3 (_pthread_sigmask+0x50d) [0x802db3bbd]
(EE) 2: /lib/libthr.so.3 (_pthread_getspecific+0xe9f) [0x802db3acf]
(EE) 3: ? (?+0xe9f) [0x800000000032]
(EE) 4: /usr/local/bin/X (dixDestroyPixmap+0x9) [0x433349]
(EE) 5: /usr/local/bin/X (dixDestroyPixmap+0x210) [0x433710]
(EE) 6: /usr/local/bin/X (UpdateCurrentTimeIf+0x3f9) [0x431889]
(EE) 7: /usr/local/bin/X (remove_fs_handlers+0x597) [0x43b627]
(EE) 8: /usr/local/bin/X (_start+0x17f) [0x424fff]
(EE) 9: ? (?+0x17f) [0x80082f57f]
(EE) 
(EE) Segmentation fault at address 0x328
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
```

Nothing gets added to dmesg for me, and nothing different from vt in /var/log/Xorg.0.log.

**Comment by MegaManSec** [comment]
editors/libreoffice4 works fine and doesn't cause any crashes.

**Comment by grahamperrin** [comment]
> On drm-next-4.7 … 

AFAICT no problem for me with the drm-next-4.7 in TrueOS Desktop, 

```
$ freebsd-version ; uname -a
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #12 8b8c812(drm-next-4.7): Wed Oct  5 19:36:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ 
```

**LibreOffice**

Version: 5.0.6.3
Build ID: FreeBSD ports 5.0.6_3
Locale: en-GB (en_GB.UTF-8)

**Comment by MegaManSec** [comment]
As stated, libreoffice4 works fine. However, when inserting images into documents, this same problem arises.
Google Docs it is, for now ;)

**Comment by grahamperrin** [comment]
I dragged a .png from Files, dropped it in a Writer window, no crash. 

Version 5.0.6.3, build ID FreeBSD ports 5.0.6_4

**Comment by nomadlogic** [comment]
I'm going to close out this issue since I can't repo on my end, and it sounds like others haven't been to repro the original issue either.
