### ISSUE TITLE
Kernel panic on i915kms module load at boot (i3-4030U)

### ISSUE THREAD

**Issue by Juanitou** [FreeBSDDesktop/freebsd-base-graphics#8]
Loading i915kms at boot time leads to this crash:

```
[drm:drm_pci_init]
drmn0: <drmn> on vgapci0
[drm:drm_get_pci_dev]


Fatal trap 12: page fault while in kernel mode
cpuid = 0; apic id = 00
fault virtual address  = 0x3b0
fault code             = supervisor read data, page not present
instruction pointer    = 0x20:0xffffffff8093d680
stack pointer          = 0x20:0xffffffff81d776b0
frame pointer          = 0x20:0xffffffff81d77720
code segment           = base 0x0, limit 0xfffff, type 0x1b
                       = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags       = interrupt enabled, resume, IOPL = 0
current process        = 0 (swapper)
[ thread pid 0 tid 100000 ]
Stopped at      __mtx_lock_sleep+0x100: movl   0x3b0(%rax),%ecx
```

**Comment by mattmacy** [comment]
can you provide a backtrace, that way I know what mutex is uninitialized

**Comment by Juanitou** [comment]
Sorry, I didn’t realize I could provide one… (shame)

```
Tracing pid 0 tid 100000 td 0xffffffff81660730
__mtx_lock_sleep() at __mtx_lock_sleep+0x100/frame 0xffffffff81d77720
idr_alloc() at idr_alloc+0x37/frame 0xffffffff81d77770
drm_minor_alloc() at drm_minor_alloc+0x79/frame 0xffffffff81d777a0
drm_dev_alloc() at drm_dev_alloc+0x238/frame 0xffffffff81d77800
drm_get_pci_dev() at drm_get_pci_dev+0x38/frame 0xffffffff81d77880
linux_pci_attach() at linux_pci_attach+0x249/frame 0xffffffff81d77960
device_attach() at device_attach+0x420/frame 0xffffffff81d779c0
bus_generic_driver_added() at bus_generic_driver_added+0x79/frame 0xffffffff81d779e0
devclass_driver_added() at devclass_driver_added+0x7d/frame 0xffffffff81d77a20
devclass_add_driver() at devclass_add_driver+0x172/frame 0xffffffff81d77a60
pci_register_driver() at pci_register_driver+0xf4/frame 0xffffffff81d77b20
_module_run() at _module_run+0x7b/frame 0xffffffff81d77b50
mi_startup() at mi_startup+0x118/frame 0xffffffff81d77b70
btext() at btext+0x2c
```

**Comment by Juanitou** [comment]
I can still reproduce this bug, with a similar backtrace, with the latest 490ab4ec68529b8f56c568d6c04095ee681760e9.

But, funnily enough, I can’t reproduce it if I set the module loading with `nextboot -e i915kms_load="YES"`. The module is cleanly loaded by the loader at boot time along linuxkpi.ko, then later in the boot sequence, DRM is loaded successfully instead of panicking as shown above.

Also, with this revision I need to use the xserver-next packages you have kindly provided to make video work, but that’s another story…

**Comment by Juanitou** [comment]
With drm-v4.7-final, the bug still exists but the panic has changed:

```
Fatal trap 12: page fault while in kernel mode
cpuid = 0; apic id = 00
fault virtual address  = 0xa8
fault code             = supervisor read data, page not present
instruction pointer    = 0x20:0xffffffff8084de53
stack pointer          = 0x28:0xffffffff81d67aa0
frame pointer          = 0x28:0xffffffff81d67b00
code segment           = base 0x0, limit 0xfffff, type 0x1b
                       = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags       = interrupt enabled, resume, IOPL = 0
current process        = 0 ()
[ thread pid 0 tid 0 ]
Stopped at      pfs_create_dir+0x33:    movq   0xa8(%r12),%rax
db> bt
Tracing pid 0 tid 0 td 0xffffffff81545ba0
pfs_create_dir() at pfs_create_dir+0x33/frame 0xffffffff81d67b00
linsysfs_create_class_dir() at linsysfs_create_class_dir+0x20/frame 0xffffffff81d67b20
fb_init() at fb_init+0xa4/frame 0xffffffff81d67b50
mi_startup() at mi_startup+0x118/frame 0xffffffff81d67b70
btext() at btext+0x2c
```

Is it useful to provide this info or the problem is well known and I should refrain from adding noise?

**Comment by mattmacy** [comment]
Priorities are, in descending order:
- New hardware support
- correctness 
- non essential graphics features
- performance 
- older hardware support
- everything else (e.g. this issue)

This isn't particularly difficult to fix, but doing so myself would come at the expense of something more important.

**Comment by kirked** [comment]
Using the `drm-next` branch last night (26-Aug 23:30 CDT) on a Dell XPS13-9350 i7 QHD(3200x1800) I get the same panic at `pfs_create_dir+0x33`: [https://github.com/FreeBSDDesktop/freebsd-base-graphics/issues/8#issuecomment-239837885].

However, I found I can `kldload i915kms` after boot just fine (but _it does_ switch me into tiny text mode (3200x1800); I usually `gop set 3` at the loader prompt to get easily readable text).

**Comment by mattmacy** [comment]
@kirked load at boot isn't supported and won't be in the near future , load it in your rc.conf.
