### ISSUE TITLE
Deadlock with SNA enabled

### ISSUE THREAD

**Issue by lattera** [FreeBSDDesktop/freebsd-base-graphics#95]
When I try to watch our favorite podcast, BSDNow, in VLC, xorg crashes and the system goes into deadlock. Fortunately, I'm returned to the console where I can see some rather interesting messages, but I can't type anything or switch to another VT. The system goes into a deadlock. Attached is a screenshot.

![img_20161003_173718](https://cloud.githubusercontent.com/assets/573797/19055203/d1f8c48c-8990-11e6-8c15-09e4d49d8ca9.jpg)

**Comment by mattmacy** [comment]
vm_page_t double free. Try using UXA.

**Comment by trombonehero** [comment]
I'm getting the same issue on a new Skylake laptop (Core i5-6200U). This happens a few times a day, leading to uptimes of minutes to hours. I've tried switching to UXA, but then I got lots of screen corruption (although the mouse cursor works properly!):

![screen corruption](https://goo.gl/photos/RKAWuaSwPwEcnkQZA)

**Comment by mattmacy** [comment]
4.8 or 4.7?

**Comment by trombonehero** [comment]
This is on 85c2f25(drm-next-4.7).

**Comment by hselasky** [comment]
Can you re-test with the latest drm-next branch?

--HPS

**Comment by trombonehero** [comment]
I can't speak for the original reporter, but I no longer see this kind of thing with the latest `drm-next`.

**Comment by lattera** [comment]
I no longer use drm-next.

**Comment by mattmacy** [comment]
Reporter can no longer test.
