### ISSUE TITLE
Atomic update failure in drm-next-4.7

### ISSUE THREAD

**Issue by trombonehero** [FreeBSDDesktop/freebsd-base-graphics#98]
I'm running 2652d2a(drm-next-4.7) on Skylake, and I am seeing lots of messages like the following:

```
Oct 12 14:00:40 fogg kernel: [drm:0xffffffff82f8ef37s] *ERROR* Atomic update
[messages.txt](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/525155/messages.txt)
 failure on pipe A (start=541133 end=541134) time 721 us, min 1073, max 1079, scanline start 1070, end 1084
Oct 12 14:01:50 fogg kernel: [drm:0xffffffff82f8ef37s] *ERROR* Atomic update failure on pipe A (start=545360 end=545361) time 0 us, min 1073, max 1079, scanline start 1071, end 1086
```
- [dmesg output](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/525154/dmesg.txt)
- [/var/log/messages](https://github.com/FreeBSDDesktop/freebsd-base-graphics/files/525158/messages.txt)

Are there additional details that would help debug this problem?

**Comment by mattmacy** [comment]
Does it happen without INVARIANTS/WITNESS?

**Comment by markjdb** [comment]
Is this still occurring?

**Comment by trombonehero** [comment]
I don't see this behaviour with recent `drm-next` any more. All clear?

**Comment by markjdb** [comment]
Sounds good to me!
