### ISSUE TITLE
dri3 .h file forgotton

### ISSUE THREAD

**Issue by MegaManSec** [FreeBSDDesktop/freebsd-base-graphics#99]
When enabling dri3 support in xorg-server via make config, dri3.h doesn't get added to the stage folder:

===>  Installing for xorg-server-1.18.4,1
[....]
===>   Registering installation for xorg-server-1.18.4,1
pkg-static: Unable to access file /usr/ports/x11-servers/xorg-server/work/stage/usr/local/include/xorg/dri3.h: No such file or directory

It is in the work folder though:

$ find . -name 'dri3.h'
./work/xorg-server-1.18.4/dri3/dri3.h

**Comment by kwm81** [comment]
I can't reproduce this. Can you run "make clean" and try again? I suspect a stale work directory.

**Comment by MegaManSec** [comment]
Yes, you're right.
Closed.
